export const expressionColors = {
  // Map emotions to our theme colors
  admiration: 'hsl(var(--color-purple))',
  adoration: 'hsl(var(--color-red))',
  aestheticAppreciation: 'hsl(var(--color-purple))',
  amusement: 'hsl(var(--color-yellow))',
  anger: 'hsl(var(--color-red))',
  annoyance: 'hsl(var(--color-red))',
  anxiety: 'hsl(var(--color-purple))',
  awe: 'hsl(var(--color-blue))',
  awkwardness: 'hsl(var(--color-yellow))',
  boredom: 'hsl(var(--color-blue))',
  calmness: 'hsl(var(--color-blue))',
  concentration: 'hsl(var(--color-blue))',
  contemplation: 'hsl(var(--color-purple))',
  confusion: 'hsl(var(--color-yellow))',
  contempt: 'hsl(var(--color-green))',
  contentment: 'hsl(var(--color-green))',
  craving: 'hsl(var(--color-green))',
  determination: 'hsl(var(--color-red))',
  disappointment: 'hsl(var(--color-blue))',
  disapproval: 'hsl(var(--color-red))',
  disgust: 'hsl(var(--color-green))',
  distress: 'hsl(var(--color-yellow))',
  doubt: 'hsl(var(--color-yellow))',
  ecstasy: 'hsl(var(--color-purple))',
  embarrassment: 'hsl(var(--color-green))',
  empathicPain: 'hsl(var(--color-red))',
  enthusiasm: 'hsl(var(--color-yellow))',
  entrancement: 'hsl(var(--color-purple))',
  envy: 'hsl(var(--color-green))',
  excitement: 'hsl(var(--color-yellow))',
  fear: 'hsl(var(--color-purple))',
  gratitude: 'hsl(var(--color-green))',
  guilt: 'hsl(var(--color-blue))',
  horror: 'hsl(var(--color-purple))',
  interest: 'hsl(var(--color-blue))',
  joy: 'hsl(var(--color-yellow))',
  love: 'hsl(var(--color-red))',
  neutral: 'hsl(var(--color-blue))',
  nostalgia: 'hsl(var(--color-purple))',
  pain: 'hsl(var(--color-red))',
  pride: 'hsl(var(--color-purple))',
  realization: 'hsl(var(--color-blue))',
  relief: 'hsl(var(--color-yellow))',
  romance: 'hsl(var(--color-yellow))',
  sadness: 'hsl(var(--color-blue))',
  sarcasm: 'hsl(var(--color-yellow))',
  satisfaction: 'hsl(var(--color-green))',
  sexualDesire: 'hsl(var(--color-red))',
  shame: 'hsl(var(--color-red))',
  surprise: 'hsl(var(--color-green))',
  surpriseNegative: 'hsl(var(--color-green))',
  surprisePositive: 'hsl(var(--color-blue))',
  sympathy: 'hsl(var(--color-blue))',
  tiredness: 'hsl(var(--color-blue))',
  triumph: 'hsl(var(--color-yellow))',
} as const;

export const isExpressionColor = (color: string): color is keyof typeof expressionColors => {
  return color in expressionColors;
};
